"""initial runs and trace_records tables

Revision ID: 130277833356
Revises: 
Create Date: 2026-05-26 20:17:43.794009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '130277833356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('providers_json', sa.Text(), nullable=False),
    sa.Column('planned_stages_json', sa.Text(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('trace_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_records')
    op.drop_table('runs')
    # ### end Alembic commands ###
